services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pillichsdorf
    ports:
      - "5432:5432"
    volumes:
      - pillichsdorf-postgres-data:/var/lib/postgresql/data

volumes:
  pillichsdorf-postgres-data:
